/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.mervyn.learn.gradle;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasGreeting() {

        Assertions.assertTrue(true);
       // todo

    }
}
